/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/charmodel.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        material={materials.Hair}
        geometry={nodes.Hair.geometry}
        position={[0, -2.86, 0]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        material={materials.Skin}
        geometry={nodes.Face.geometry}
        position={[0, -2.86, 0]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        material={materials.Eyes}
        geometry={nodes.Eyes.geometry}
        position={[0, -2.86, 0]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        material={materials.Eyebrows}
        geometry={nodes.Eyebrows.geometry}
        position={[0, -2.86, 0]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        material={materials.Shirt}
        geometry={nodes.Shirt.geometry}
        position={[0, -2.86, 0]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        material={materials.HairBase}
        geometry={nodes.Skull.geometry}
        position={[0, -2.86, 0]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        material={materials.Jacket}
        geometry={nodes.Jacket.geometry}
        position={[0, -2.86, 0]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        material={materials.LightJacket}
        geometry={nodes.Cuffs.geometry}
        position={[0, -2.86, 0]}
        rotation={[Math.PI / 2, 0, 0]}
      />
    </group>
  )
}

useGLTF.preload('/charmodel.glb')
