/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function RoomModel(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/room.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh name="Floor" geometry={nodes.Floor.geometry} material={materials.Carpet} scale={[3, 3, 4.5]} />
        <mesh
          name="Side_Wall"
          geometry={nodes.Side_Wall.geometry}
          material={nodes.Side_Wall.material}
          position={[0, 1.5, -4.5]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[1, 0.5, 1]}
        />
        <mesh
          name="Back_Wall"
          geometry={nodes.Back_Wall.geometry}
          material={nodes.Back_Wall.material}
          position={[-3, 1.5, 0]}
          rotation={[0, 0, -Math.PI / 2]}
          scale={[2, 1, 3]}
        />
        <group
          name="Door"
          position={[-2.95, 0, -0.65]}
          rotation={[Math.PI / 2, 0, -Math.PI / 2]}
          scale={[0.06, 0.06, 0.06]}>
          <mesh name="Door_188" geometry={nodes.Door_188.geometry} material={materials.DoorFrameWood} />
          <mesh name="Door_188_1" geometry={nodes.Door_188_1.geometry} material={materials.DoorWood} />
          <mesh name="Door_188_2" geometry={nodes.Door_188_2.geometry} material={materials.DoorKnob} />
        </group>
        <mesh
          name="Screen"
          geometry={nodes.Screen.geometry}
          material={materials.Screen}
          position={[-0.8, 1.48, -3.71]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[0.87, 1, 0.63]}
        />
        <group name="Desk">
        <mesh
          name="DeskLeg001"
          geometry={nodes.DeskLeg001.geometry}
          material={nodes.DeskLeg001.material}
          position={[-1.72, 0.54, -2.85]}
          rotation={[Math.PI / 2, 0, -Math.PI / 2]}
          scale={1.17}
        />
        <mesh
          name="DeskDrawerTop001"
          geometry={nodes.DeskDrawerTop001.geometry}
          material={nodes.DeskDrawerTop001.material}
          position={[-1.72, 0.54, -2.85]}
          rotation={[Math.PI / 2, 0, -Math.PI / 2]}
          scale={1.17}
        />
        <group
          name="DeskLegBase001"
          position={[-1.72, 0.54, -2.85]}
          rotation={[Math.PI / 2, 0, -Math.PI / 2]}
          scale={1.17}>
          <mesh
            name="group122835016"
            geometry={nodes.group122835016.geometry}
            material={nodes.group122835016.material}
          />
          <mesh
            name="group122835016_1"
            geometry={nodes.group122835016_1.geometry}
            material={nodes.group122835016_1.material}
          />
        </group>
        <mesh
          name="DeskDrawerTop002"
          geometry={nodes.DeskDrawerTop002.geometry}
          material={nodes.DeskDrawerTop002.material}
          position={[-1.72, 0.54, -2.85]}
          rotation={[Math.PI / 2, 0, -Math.PI / 2]}
          scale={1.17}
        />
        <mesh
          name="DeskDrawerTop"
          geometry={nodes.DeskDrawerTop.geometry}
          material={nodes.DeskDrawerTop.material}
          position={[-1.72, 0.54, -2.85]}
          rotation={[Math.PI / 2, 0, -Math.PI / 2]}
          scale={1.17}
        />
        <mesh
          name="DeskHandle001"
          geometry={nodes.DeskHandle001.geometry}
          material={nodes.DeskHandle001.material}
          position={[-1.72, 0.54, -2.85]}
          rotation={[Math.PI / 2, 0, -Math.PI / 2]}
          scale={1.17}
        />
        <mesh
          name="DeskWall002"
          geometry={nodes.DeskWall002.geometry}
          material={nodes.DeskWall002.material}
          position={[-1.72, 0.54, -2.85]}
          rotation={[Math.PI / 2, 0, -Math.PI / 2]}
          scale={1.17}
        />
        <mesh
          name="DeskHandle"
          geometry={nodes.DeskHandle.geometry}
          material={nodes.DeskHandle.material}
          position={[-1.72, 0.54, -2.85]}
          rotation={[Math.PI / 2, 0, -Math.PI / 2]}
          scale={1.17}
        />
        <mesh
          name="DeskDrawerFront001"
          geometry={nodes.DeskDrawerFront001.geometry}
          material={nodes.DeskDrawerFront001.material}
          position={[-1.72, 0.54, -2.85]}
          rotation={[Math.PI / 2, 0, -Math.PI / 2]}
          scale={1.17}
        />
        <mesh
          name="DeskHandle002"
          geometry={nodes.DeskHandle002.geometry}
          material={nodes.DeskHandle002.material}
          position={[-1.72, 0.54, -2.85]}
          rotation={[Math.PI / 2, 0, -Math.PI / 2]}
          scale={1.17}
        />
        <mesh
          name="DeskDrawerFront002"
          geometry={nodes.DeskDrawerFront002.geometry}
          material={nodes.DeskDrawerFront002.material}
          position={[-1.72, 0.54, -2.85]}
          rotation={[Math.PI / 2, 0, -Math.PI / 2]}
          scale={1.17}
        />
        <mesh
          name="DeskLeg"
          geometry={nodes.DeskLeg.geometry}
          material={nodes.DeskLeg.material}
          position={[-1.72, 0.54, -2.85]}
          rotation={[Math.PI / 2, 0, -Math.PI / 2]}
          scale={1.17}
        />
        <mesh
          name="DeskWall001"
          geometry={nodes.DeskWall001.geometry}
          material={nodes.DeskWall001.material}
          position={[-1.72, 0.54, -2.85]}
          rotation={[Math.PI / 2, 0, -Math.PI / 2]}
          scale={1.17}
        />
        <mesh
          name="DeskWall003"
          geometry={nodes.DeskWall003.geometry}
          material={nodes.DeskWall003.material}
          position={[-1.72, 0.54, -2.85]}
          rotation={[Math.PI / 2, 0, -Math.PI / 2]}
          scale={1.17}
        />
        <mesh
          name="DeskWall004"
          geometry={nodes.DeskWall004.geometry}
          material={nodes.DeskWall004.material}
          position={[-1.72, 0.54, -2.85]}
          rotation={[Math.PI / 2, 0, -Math.PI / 2]}
          scale={1.17}
        />
        <mesh
          name="DeskLegBase"
          geometry={nodes.DeskLegBase.geometry}
          material={nodes.DeskLegBase.material}
          position={[-1.72, 0.54, -2.85]}
          rotation={[Math.PI / 2, 0, -Math.PI / 2]}
          scale={1.17}
        />
        <mesh
          name="DeskDrawerFront"
          geometry={nodes.DeskDrawerFront.geometry}
          material={nodes.DeskDrawerFront.material}
          position={[-1.72, 0.54, -2.85]}
          rotation={[Math.PI / 2, 0, -Math.PI / 2]}
          scale={1.17}
        />
        <mesh
          name="DeskWall"
          geometry={nodes.DeskWall.geometry}
          material={nodes.DeskWall.material}
          position={[-1.72, 0.54, -2.85]}
          rotation={[Math.PI / 2, 0, -Math.PI / 2]}
          scale={1.17}
        />
        <mesh
          name="DeskSurface"
          geometry={nodes.DeskSurface.geometry}
          material={nodes.DeskSurface.material}
          position={[-1.72, 0.54, -2.85]}
          rotation={[Math.PI / 2, 0, -Math.PI / 2]}
          scale={1.17}
        />
        <mesh
          name="Computer"
          geometry={nodes.Computer.geometry}
          material={materials.Computer_mat1}
          position={[-0.8, 1.11, -3.48]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.14}
        />
        </group>
        <group name="Chair">
        <mesh
          name="ChairBackBar001"
          geometry={nodes.ChairBackBar001.geometry}
          material={nodes.ChairBackBar001.material}
          position={[-0.84, 0.45, -2.08]}
          rotation={[Math.PI / 2, 0, Math.PI]}
          scale={1.21}
        />
        <mesh
          name="ChairBackBar002"
          geometry={nodes.ChairBackBar002.geometry}
          material={nodes.ChairBackBar002.material}
          position={[-0.84, 0.45, -2.08]}
          rotation={[Math.PI / 2, 0, Math.PI]}
          scale={1.21}
        />
        <mesh
          name="ChairBaseX"
          geometry={nodes.ChairBaseX.geometry}
          material={nodes.ChairBaseX.material}
          position={[-0.84, 0.45, -2.08]}
          rotation={[Math.PI / 2, 0, Math.PI]}
          scale={1.21}
        />
        <mesh
          name="ChairBackBar003"
          geometry={nodes.ChairBackBar003.geometry}
          material={nodes.ChairBackBar003.material}
          position={[-0.84, 0.45, -2.08]}
          rotation={[Math.PI / 2, 0, Math.PI]}
          scale={1.21}
        />
        <mesh
          name="ChairBack"
          geometry={nodes.ChairBack.geometry}
          material={nodes.ChairBack.material}
          position={[-0.84, 0.45, -2.08]}
          rotation={[Math.PI / 2, 0, Math.PI]}
          scale={1.21}
        />
        <mesh
          name="ChairAdjustPedal"
          geometry={nodes.ChairAdjustPedal.geometry}
          material={nodes.ChairAdjustPedal.material}
          position={[-0.84, 0.45, -2.08]}
          rotation={[Math.PI / 2, 0, Math.PI]}
          scale={1.21}
        />
        <mesh
          name="ChairSeat"
          geometry={nodes.ChairSeat.geometry}
          material={nodes.ChairSeat.material}
          position={[-0.84, 0.45, -2.08]}
          rotation={[Math.PI / 2, 0, Math.PI]}
          scale={1.21}
        />
        <group name="ChairWheel001" position={[-0.84, 0.45, -2.08]} rotation={[Math.PI / 2, 0, Math.PI]} scale={1.21}>
          <mesh
            name="group1306767648"
            geometry={nodes.group1306767648.geometry}
            material={nodes.group1306767648.material}
          />
          <mesh
            name="group1306767648_1"
            geometry={nodes.group1306767648_1.geometry}
            material={nodes.group1306767648_1.material}
          />
          <mesh
            name="group1306767648_2"
            geometry={nodes.group1306767648_2.geometry}
            material={nodes.group1306767648_2.material}
          />
        </group>
        <group name="ChairWheel002" position={[-0.84, 0.45, -2.08]} rotation={[Math.PI / 2, 0, Math.PI]} scale={1.21}>
          <mesh
            name="group1665730989"
            geometry={nodes.group1665730989.geometry}
            material={nodes.group1665730989.material}
          />
          <mesh
            name="group1665730989_1"
            geometry={nodes.group1665730989_1.geometry}
            material={nodes.group1665730989_1.material}
          />
          <mesh
            name="group1665730989_2"
            geometry={nodes.group1665730989_2.geometry}
            material={nodes.group1665730989_2.material}
          />
        </group>
        <mesh
          name="ChairBackBar"
          geometry={nodes.ChairBackBar.geometry}
          material={nodes.ChairBackBar.material}
          position={[-0.84, 0.45, -2.08]}
          rotation={[Math.PI / 2, 0, Math.PI]}
          scale={1.21}
        />
        <mesh
          name="ChairUnderSeat"
          geometry={nodes.ChairUnderSeat.geometry}
          material={nodes.ChairUnderSeat.material}
          position={[-0.84, 0.45, -2.08]}
          rotation={[Math.PI / 2, 0, Math.PI]}
          scale={1.21}
        />
        <group name="ChairWheel003" position={[-0.84, 0.45, -2.08]} rotation={[Math.PI / 2, 0, Math.PI]} scale={1.21}>
          <mesh
            name="group1933021004"
            geometry={nodes.group1933021004.geometry}
            material={nodes.group1933021004.material}
          />
          <mesh
            name="group1933021004_1"
            geometry={nodes.group1933021004_1.geometry}
            material={nodes.group1933021004_1.material}
          />
          <mesh
            name="group1933021004_2"
            geometry={nodes.group1933021004_2.geometry}
            material={nodes.group1933021004_2.material}
          />
        </group>
        <mesh
          name="ChairCentreMainBar"
          geometry={nodes.ChairCentreMainBar.geometry}
          material={nodes.ChairCentreMainBar.material}
          position={[-0.84, 0.45, -2.08]}
          rotation={[Math.PI / 2, 0, Math.PI]}
          scale={1.21}
        />
        <mesh
          name="ChairAdjustTip"
          geometry={nodes.ChairAdjustTip.geometry}
          material={nodes.ChairAdjustTip.material}
          position={[-0.84, 0.45, -2.08]}
          rotation={[Math.PI / 2, 0, Math.PI]}
          scale={1.21}
        />
        <group name="ChairWheel" position={[-0.84, 0.45, -2.08]} rotation={[Math.PI / 2, 0, Math.PI]} scale={1.21}>
          <mesh
            name="group2136273154"
            geometry={nodes.group2136273154.geometry}
            material={nodes.group2136273154.material}
          />
          <mesh
            name="group2136273154_1"
            geometry={nodes.group2136273154_1.geometry}
            material={nodes.group2136273154_1.material}
          />
          <mesh
            name="group2136273154_2"
            geometry={nodes.group2136273154_2.geometry}
            material={nodes.group2136273154_2.material}
          />
        </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/room.glb')
