/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useFrame } from "@react-three/fiber";
import { useGLTF } from '@react-three/drei';
import { RainbowShader } from "./shaders/RainbowShader";

//Consider following tutorial:
//https://codesandbox.io/s/react-three-fiber-custom-geometry-with-fragment-shader-material-vxswf?file=/src/index.js:2318-2328

export default function UserModel(props) {
  const group = useRef();
  const ref = useRef();
  //const [hovered, setHover] = useState(false);
  const { nodes } = useGLTF('/user.glb');

  
  useFrame((() => {
    ref.current.material.uniforms.time.value += 0.1
  }));

  //geometry={nodes.Head.geometry}
  //material={nodes.Head.material}
  //material={nodes.RightEye.material}
  //material={nodes.LeftEye.material}
  //                  onClick={e => console.log("click")}
  //onPointerMove={e => setHover(true)}
  //onPointerOut={e => setHover(false)}

  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[0, -6.59, 0]} scale={[6.51, 6.51, 6.51]}>
        <group position={[0, 1.13, -0.01]} rotation={[-0.01, 0, 0]}>
          <group position={[0, 0.53, 0]} rotation={[0.59, 0, 0]}>
            <group position={[0, 0.04, 0]} rotation={[-0.32, 0, 0]}>
              <group position={[0, 0.05, 0]} rotation={[-0.26, 0, 0]}>
                <mesh
                  geometry={nodes.Head.geometry}
                  material={nodes.Head.material}
                  position={[0, 0.13, 0]}
                  rotation={[1.41, -1.57, 1.41]}
                  scale={[0.09, 0.15, 0.12]}
                >
                </mesh>
                <mesh
                  geometry={nodes.LeftEye.geometry}
                  position={[0.03, 0.13, 0.08]}
                  rotation={[3.14, -0.14, 3.14]}
                  scale={[0.02, 0.01, 0.01]}
                >
                  <shaderMaterial
                    attach="material"
                    args={[RainbowShader]}
                  />
                </mesh>
                <mesh
                  ref={ref}
                  geometry={nodes.RightEye.geometry}
                  position={[-0.04, 0.13, 0.08]}
                  rotation={[-3.14, 0.15, 3.14]}
                  scale={[0.02, 0.01, 0.01]}
                >
                  <shaderMaterial
                    attach="material"
                    args={[RainbowShader]}
                  />
                </mesh>
              </group>
              <mesh
                geometry={nodes.Neck.geometry}
                material={nodes.Neck.material}
                position={[0, 0.03, 0.01]}
                rotation={[-0.26, -Math.PI / 2, 0]}
                scale={[0.05, 0.05, 0.05]}
              />
            </group>
          </group>
          <group position={[0.02, 0.47, 0.08]} rotation={[-1.56, -0.02, -1.04]}>
            <group position={[0.09, 0.18, -0.01]} rotation={[1.13, 0.98, -2.65]}>
              <group position={[0, 0.33, 0]} rotation={[1.11, -0.44, -0.2]}>
                <group position={[0, 0.33, 0]} rotation={[0.11, 0.1, -0.09]}>
                  <mesh
                    geometry={nodes.Finger008.geometry}
                    material={nodes.Finger008.material}
                    position={[-0.05, 0.05, 0.01]}
                    rotation={[3.1, -0.01, 2.87]}
                    scale={[-0.01, -0.02, 0]}
                  />
                  <mesh
                    geometry={nodes.Finger009.geometry}
                    material={nodes.Finger009.material}
                    position={[-0.03, 0.06, 0.01]}
                    rotation={[3.1, -0.01, -0.25]}
                    scale={[0.01, 0.03, 0.01]}
                  />
                  <mesh
                    geometry={nodes.Finger010.geometry}
                    material={nodes.Finger010.material}
                    position={[-0.01, 0.07, 0.01]}
                    rotation={[3.1, -0.01, -0.1]}
                    scale={[0.01, 0.03, 0.01]}
                  />
                  <mesh
                    geometry={nodes.Finger011.geometry}
                    material={nodes.Finger011.material}
                    position={[0.01, 0.07, 0.01]}
                    rotation={[3.1, -0.01, 0.06]}
                    scale={[0.01, 0.03, 0.01]}
                  />
                  <mesh
                    geometry={nodes.Finger012.geometry}
                    material={nodes.Finger012.material}
                    position={[-0.06, 0.09, 0.01]}
                    rotation={[3.1, -0.01, 2.97]}
                    scale={[-0.01, -0.02, 0]}
                  />
                  <mesh
                    geometry={nodes.Finger013.geometry}
                    material={nodes.Finger013.material}
                    position={[-0.04, 0.1, 0.01]}
                    rotation={[3.1, -0.01, 2.97]}
                    scale={[-0.01, -0.02, 0]}
                  />
                  <mesh
                    geometry={nodes.Finger014.geometry}
                    material={nodes.Finger014.material}
                    position={[-0.01, 0.11, 0.01]}
                    rotation={[3.1, -0.01, 3.02]}
                    scale={[-0.01, -0.02, 0]}
                  />
                  <mesh
                    geometry={nodes.Finger015.geometry}
                    material={nodes.Finger015.material}
                    position={[0.01, 0.11, 0.01]}
                    rotation={[3.1, -0.01, 3.13]}
                    scale={[-0.01, -0.02, 0]}
                  />
                  <mesh
                    geometry={nodes.Hand001.geometry}
                    material={nodes.Hand001.material}
                    position={[-0.01, 0.02, 0.01]}
                    rotation={[3.1, -0.01, -0.17]}
                    scale={[0.06, 0.06, 0.03]}
                  />
                  <mesh
                    geometry={nodes.Thumb002.geometry}
                    material={nodes.Thumb002.material}
                    position={[0.03, 0.04, 0.01]}
                    rotation={[3.1, -0.01, 0.31]}
                    scale={[0.01, 0.03, 0.01]}
                  />
                  <mesh
                    geometry={nodes.Thumb003.geometry}
                    material={nodes.Thumb003.material}
                    position={[0.04, 0.08, 0.01]}
                    rotation={[3.1, -0.01, 0.02]}
                    scale={[0.01, 0.01, 0.01]}
                  />
                </group>
                <mesh
                  geometry={nodes.Elbow.geometry}
                  material={nodes.Elbow.material}
                  position={[0, -0.01, 0.01]}
                  rotation={[-2.71, 1.49, 2.7]}
                  scale={[-0.05, -0.05, -0.05]}
                />
                <mesh
                  geometry={nodes.LowerArm.geometry}
                  material={nodes.LowerArm.material}
                  position={[0, 0.17, 0.01]}
                  rotation={[0.3, -1.49, 0.32]}
                  scale={[0.2, 0.14, 0.2]}
                />
              </group>
              <mesh
                geometry={nodes.UpperArm.geometry}
                material={nodes.UpperArm.material}
                position={[0, 0.19, 0]}
                rotation={[2.96, -1.47, 2.84]}
                scale={[0.2, 0.14, 0.2]}
              >
                                            <shaderMaterial
              attach="material"
              args={[RainbowShader]}
            />
              </mesh>
            </group>
            <mesh
              geometry={nodes.Shoulder.geometry}
              material={nodes.Shoulder.material}
              position={[0.06, 0.19, -0.01]}
              rotation={[1.57, -0.53, -3.14]}
              scale={[0.09, 0.1, 0.1]}
            />
          </group>
          <group position={[-0.02, 0.47, 0.08]} rotation={[-1.56, -0.01, 1.29]}>
            <group position={[-0.01, 0.19, -0.02]} rotation={[0.82, -1.08, 2.29]}>
              <group position={[0, 0.35, 0]} rotation={[1.03, 0.72, 0.04]}>
                <group position={[0, 0.32, 0]} rotation={[0.07, -0.06, -0.03]}>
                  <mesh
                    geometry={nodes.Finger000.geometry}
                    material={nodes.Finger000.material}
                    position={[0.03, 0.06, 0]}
                    rotation={[-0.05, 0, -0.03]}
                    scale={[-0.01, -0.02, 0]}
                  />
                  <mesh
                    geometry={nodes.Finger001.geometry}
                    material={nodes.Finger001.material}
                    position={[0.01, 0.07, 0]}
                    rotation={[-0.05, 0, 3.13]}
                    scale={[0.01, 0.03, 0.01]}
                  />
                  <mesh
                    geometry={nodes.Finger002.geometry}
                    material={nodes.Finger002.material}
                    position={[-0.01, 0.07, 0]}
                    rotation={[-0.05, 0, -3.01]}
                    scale={[0.01, 0.03, 0.01]}
                  />
                  <mesh
                    geometry={nodes.Finger003.geometry}
                    material={nodes.Finger003.material}
                    position={[-0.03, 0.06, 0]}
                    rotation={[-0.05, 0, -2.85]}
                    scale={[0.01, 0.03, 0.01]}
                  />
                  <mesh
                    geometry={nodes.Finger004.geometry}
                    material={nodes.Finger004.material}
                    position={[0.03, 0.1, 0]}
                    rotation={[-0.05, 0, 0.07]}
                    scale={[-0.01, -0.02, 0]}
                  />
                  <mesh
                    geometry={nodes.Finger005.geometry}
                    material={nodes.Finger005.material}
                    position={[0.01, 0.11, 0]}
                    rotation={[-0.05, 0, 0.07]}
                    scale={[-0.01, -0.02, 0]}
                  />
                  <mesh
                    geometry={nodes.Finger006.geometry}
                    material={nodes.Finger006.material}
                    position={[-0.01, 0.11, 0]}
                    rotation={[-0.05, 0, 0.12]}
                    scale={[-0.01, -0.02, 0]}
                  />
                  <mesh
                    geometry={nodes.Finger007.geometry}
                    material={nodes.Finger007.material}
                    position={[-0.04, 0.1, 0]}
                    rotation={[-0.05, 0, 0.23]}
                    scale={[-0.01, -0.02, 0]}
                  />
                  <mesh
                    geometry={nodes.Hand.geometry}
                    material={nodes.Hand.material}
                    position={[0, 0.02, 0.01]}
                    rotation={[-0.05, 0, -3.08]}
                    scale={[0.06, 0.06, 0.03]}
                  />
                  <mesh
                    geometry={nodes.Thumb.geometry}
                    material={nodes.Thumb.material}
                    position={[-0.04, 0.03, 0.01]}
                    rotation={[-0.05, 0, -2.6]}
                    scale={[0.01, 0.03, 0.01]}
                  />
                  <mesh
                    geometry={nodes.Thumb001.geometry}
                    material={nodes.Thumb001.material}
                    position={[-0.05, 0.06, 0]}
                    rotation={[-0.05, 0, -2.89]}
                    scale={[0.01, 0.01, 0.01]}
                  />
                </group>
                <mesh
                  geometry={nodes.RightElbow.geometry}
                  material={nodes.RightElbow.material}
                  position={[0.01, -0.01, 0]}
                  rotation={[-0.47, 1.5, -2.65]}
                  scale={[0.05, 0.05, 0.05]}
                />
                <mesh
                  geometry={nodes.RightLowerArm.geometry}
                  material={nodes.RightLowerArm.material}
                  position={[0.01, 0.16, 0]}
                  rotation={[2.81, -1.5, -0.35]}
                  scale={[-0.2, -0.14, -0.2]}
                />
              </group>
              <mesh
                geometry={nodes.RightUpperArm.geometry}
                
                position={[0.01, 0.21, 0]}
                rotation={[-0.08, -1.48, 3.06]}
                scale={[-0.2, -0.14, -0.2]}
              >
                            <shaderMaterial
              attach="material"
              args={[RainbowShader]}
            />
                </mesh>
            </group>
            <mesh
              geometry={nodes.RightShoulder.geometry}
              material={nodes.RightShoulder.material}
              position={[-0.01, 0.2, -0.01]}
              rotation={[-1.57, -0.28, 3.14]}
              scale={[-0.09, -0.1, -0.1]}
            />
          </group>
          <mesh
          
            geometry={nodes.Chest.geometry}
            position={[0, 0.18, 0.03]}
            rotation={[0.03, Math.PI / 2, 0]}
            scale={[-0.1, -0.44, -0.15]}
          >
            <shaderMaterial
              attach="material"
              args={[RainbowShader]}
            />
            </mesh>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/user.glb')

//            material={nodes.Chest.material}
//material={nodes.RightUpperArm.material}